dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
      - dhananjaypatil070@gmail.com
    on_success: always
    on_failure: always
node_js:
  - "9"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
install:
  - npm install
  - npm install -g mocha
before_script:
script:
after_script: